### ISSUE TITLE
Connecting from Android

### ISSUE THREAD

**Issue by audetto** [dodgyrabbit/midi-ble-bridge#1]
Have you been able to connect to your gatt-server from an Android phone?

I can scan but it does not work afterwards, with absolutely no visible output or errors.

I use https://play.google.com/store/apps/details?id=com.mobileer.example.midibtlepairing&hl=en

**Comment by dodgyrabbit** [comment]
FYI I used https://play.google.com/store/apps/details?id=no.nordicsemi.android.mcp&hl=en_US&gl=US to figure out what is going on.
